# Generated by Django 3.2.12 on 2022-03-19 16:26

import colorfield.fields
from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddingCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=70)),
                ('company_name', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('company_link', models.CharField(max_length=300)),
                ('company_phone', models.CharField(max_length=70)),
                ('about_company', models.TextField()),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Added Companies',
            },
        ),
        migrations.CreateModel(
            name='Hobbies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hobby', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name': 'Hobby (for Resume)',
                'verbose_name_plural': 'Hobbies (for Resume)',
            },
        ),
        migrations.CreateModel(
            name='requiredskills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skills', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Required Skill (for JobPost)',
                'verbose_name_plural': 'Required Skills (for JobPost)',
            },
        ),
        migrations.CreateModel(
            name='ResumeColors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color1', colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=18, samples=None)),
                ('color2', colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=18, samples=None)),
                ('color3', colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=18, samples=None)),
                ('color4', colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=18, samples=None)),
                ('color5', colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=18, samples=None)),
                ('color6', colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=18, samples=None)),
            ],
            options={
                'verbose_name': 'Color',
                'verbose_name_plural': 'Colors',
            },
        ),
        migrations.CreateModel(
            name='socialmedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_name', models.CharField(max_length=30)),
                ('link', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name': 'Social Media (for Resume)',
                'verbose_name_plural': 'Social Media (for Resume)',
            },
        ),
        migrations.CreateModel(
            name='ResumeSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, upload_to='')),
                ('first_name', models.CharField(max_length=250)),
                ('last_name', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('coutry', django_countries.fields.CountryField(max_length=2)),
                ('region', models.CharField(max_length=70)),
                ('district', models.CharField(max_length=70)),
                ('quarter', models.CharField(max_length=100)),
                ('street', models.CharField(max_length=150)),
                ('skills_select', models.CharField(max_length=70)),
                ('your_skills', models.CharField(max_length=70)),
                ('language', models.CharField(max_length=70)),
                ('about_you', models.TextField()),
                ('website_link', models.CharField(max_length=250)),
                ('company_name', models.CharField(max_length=150)),
                ('role', models.CharField(max_length=150)),
                ('university', models.CharField(max_length=150)),
                ('degree', models.CharField(max_length=150)),
                ('info', models.TextField()),
                ('hobbies', models.ManyToManyField(to='mainAPI.Hobbies')),
                ('social_media', models.ManyToManyField(to='mainAPI.socialmedia')),
            ],
            options={
                'verbose_name': 'Resume',
                'verbose_name_plural': 'Resumes',
            },
        ),
        migrations.CreateModel(
            name='JobPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('freelancer_type', models.CharField(max_length=100)),
                ('location', django_countries.fields.CountryField(max_length=2)),
                ('price', models.IntegerField()),
                ('description', models.TextField()),
                ('skills', models.ManyToManyField(to='mainAPI.requiredskills')),
            ],
            options={
                'verbose_name': 'Post Job',
                'verbose_name_plural': 'Posted Jobs',
            },
        ),
    ]
