# Generated by Django 3.2.12 on 2022-12-05 08:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university', models.CharField(max_length=150)),
                ('degree', models.CharField(max_length=150)),
                ('info', models.TextField()),
            ],
            options={
                'verbose_name': 'Education',
                'verbose_name_plural': 'Education',
            },
        ),
        migrations.CreateModel(
            name='experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, max_length=150, null=True)),
                ('role', models.CharField(blank=True, max_length=150, null=True)),
                ('info', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Experience',
                'verbose_name_plural': 'Experience',
            },
        ),
        migrations.CreateModel(
            name='hobbies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name': 'Hobby (for Resume)',
                'verbose_name_plural': 'Hobbies (for Resume)',
            },
        ),
        migrations.CreateModel(
            name='language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Language',
                'verbose_name_plural': 'Languages',
            },
        ),
        migrations.CreateModel(
            name='requiredskills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Required Skill (for JobPost)',
                'verbose_name_plural': 'Required Skills (for JobPost)',
            },
        ),
        migrations.CreateModel(
            name='socialmedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('link', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name': 'Social Media (for Resume)',
                'verbose_name_plural': 'Social Media (for Resume)',
            },
        ),
        migrations.CreateModel(
            name='ResumeSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_type', models.CharField(choices=[('1', 'Template 1'), ('2', 'Template 2'), ('3', 'Template 3'), ('4', 'Template 4'), ('5', 'Template 5')], default='1', max_length=1)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='')),
                ('first_name', models.CharField(max_length=250)),
                ('last_name', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('country', models.CharField(max_length=100)),
                ('region', models.CharField(blank=True, max_length=70, null=True)),
                ('district', models.CharField(blank=True, max_length=70, null=True)),
                ('quarter', models.CharField(blank=True, max_length=100, null=True)),
                ('street', models.CharField(blank=True, max_length=150, null=True)),
                ('about_you', models.TextField(blank=True, null=True)),
                ('website_link', models.CharField(blank=True, max_length=250, null=True)),
                ('twitter', models.CharField(blank=True, max_length=500, null=True)),
                ('linkedin', models.CharField(blank=True, max_length=500, null=True)),
                ('instagram', models.CharField(blank=True, max_length=500, null=True)),
                ('facebook', models.CharField(blank=True, max_length=500, null=True)),
                ('education', models.ManyToManyField(blank=True, to='mainAPI.education')),
                ('experience', models.ManyToManyField(blank=True, to='mainAPI.experience')),
                ('hobbies', models.ManyToManyField(to='mainAPI.hobbies')),
                ('language', models.ManyToManyField(to='mainAPI.language')),
                ('skills_select', models.ManyToManyField(blank=True, related_name='resumeSkills', to='mainAPI.requiredskills')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Resume',
                'verbose_name_plural': 'Resumes',
            },
        ),
        migrations.CreateModel(
            name='JobPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('freelancer_type', models.CharField(max_length=100)),
                ('location', django_countries.fields.CountryField(blank=True, max_length=2, null=True)),
                ('price', models.IntegerField()),
                ('description', models.TextField()),
                ('skills', models.ManyToManyField(to='mainAPI.requiredskills')),
            ],
            options={
                'verbose_name': 'Post Job',
                'verbose_name_plural': 'Posted Jobs',
            },
        ),
        migrations.CreateModel(
            name='AddingCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(max_length=70)),
                ('img', models.ImageField(blank=True, upload_to='')),
                ('company_name', models.CharField(max_length=200)),
                ('number', models.CharField(blank=True, max_length=50)),
                ('location', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('website_link', models.CharField(blank=True, max_length=300)),
                ('whatsapp', models.CharField(blank=True, max_length=300)),
                ('facebook', models.CharField(blank=True, max_length=300)),
                ('instagram', models.CharField(blank=True, max_length=300)),
                ('telegram', models.CharField(blank=True, max_length=300)),
                ('github', models.CharField(blank=True, max_length=300)),
                ('twitter', models.CharField(blank=True, max_length=300)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Added Companies',
            },
        ),
    ]
