# Generated by Django 3.2.12 on 2022-03-19 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainAPI', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddingCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=70)),
                ('company_name', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('company_link', models.CharField(max_length=300)),
                ('company_phone', models.CharField(max_length=70)),
                ('about_company', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Jobs',
        ),
        migrations.DeleteModel(
            name='test',
        ),
    ]
