# Generated by Django 3.2.12 on 2022-03-19 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainAPI', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumesection',
            name='one_to_one',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainAPI.requiredskills'),
        ),
    ]
