# Generated by Django 3.2.12 on 2022-03-31 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainAPI', '0002_resumesection_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resumesection',
            name='your_skills',
        ),
    ]
