# Generated by Django 3.2.12 on 2022-03-19 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default=None, max_length=155),
            preserve_default=False,
        ),
    ]
